/**
 * Códigos de los sitios de medición que piden los métodos del motor, con el patrón de 05.1
 * (assessment.measurement_site.code). La semilla del catálogo (P7) usa estos mismos códigos.
 */
export const SITES = {
  BASIC_WEIGHT: 'BASIC_WEIGHT',
  BASIC_HEIGHT: 'BASIC_HEIGHT',
  BASIC_SITTING_HEIGHT: 'BASIC_SITTING_HEIGHT',
  SKF_TRICEPS: 'SKF_TRICEPS',
  SKF_SUBSCAPULAR: 'SKF_SUBSCAPULAR',
  SKF_BICEPS: 'SKF_BICEPS',
  SKF_ILIAC_CREST: 'SKF_ILIAC_CREST',
  SKF_SUPRASPINALE: 'SKF_SUPRASPINALE',
  SKF_ABDOMINAL: 'SKF_ABDOMINAL',
  SKF_FRONT_THIGH: 'SKF_FRONT_THIGH',
  SKF_MEDIAL_CALF: 'SKF_MEDIAL_CALF',
  /** Sitios extra del protocolo de Jackson y Pollock, fuera del perfil ISAK (RN-D04). */
  SKF_CHEST: 'SKF_CHEST',
  SKF_MIDAXILLARY: 'SKF_MIDAXILLARY',
  SKF_SUPRAILIAC: 'SKF_SUPRAILIAC',
  GIRTH_HEAD: 'GIRTH_HEAD',
  GIRTH_ARM_RELAXED: 'GIRTH_ARM_RELAXED',
  GIRTH_FOREARM: 'GIRTH_FOREARM',
  GIRTH_CHEST: 'GIRTH_CHEST',
  GIRTH_WAIST: 'GIRTH_WAIST',
  GIRTH_HIP: 'GIRTH_HIP',
  GIRTH_THIGH: 'GIRTH_THIGH',
  GIRTH_CALF: 'GIRTH_CALF',
  BREADTH_HUMERUS: 'BREADTH_HUMERUS',
  BREADTH_WRIST: 'BREADTH_WRIST',
  BREADTH_FEMUR: 'BREADTH_FEMUR',
  BREADTH_BIACROMIAL: 'BREADTH_BIACROMIAL',
  BREADTH_BIILIOCRISTAL: 'BREADTH_BIILIOCRISTAL',
  BREADTH_TRANSVERSE_CHEST: 'BREADTH_TRANSVERSE_CHEST',
  BREADTH_AP_CHEST: 'BREADTH_AP_CHEST',
} as const;

export type SiteCode = (typeof SITES)[keyof typeof SITES];
